using Ede.Uofx.FormSchema.UofxFormSchema;
using Ede.Uofx.PubApi.Sdk.NetStd.Models.Base;
using Ede.Uofx.PubApi.Sdk.NetStd.Service;

namespace ConsoleApp1
{
    internal class Program
    {
        async static Task  Main(string[] args)
        {
            //eyJDbGllbnRJZCI6IjY2YTM4MzFjLTQyNTMtNGQxZC0xYmIyLTA4ZGM2OGVjZjA1NCIsIlByaXZhdGVLZXkiOiJQRkpUUVV0bGVWWmhiSFZsUGp4TmIyUjFiSFZ6UG1zd1ZYTXJXRk5oY2tKdFRYZHFUR1F3TDBSUldURTNMMVp4ZUhSbWJ6aGlWbEp3ZVdnMmFuWTFhUzl2VkRadVFYbGhOVVZ6Ykc1RWJGVkNTbWxCWVVrdlExTjNOWFpvTnpJMlYzcFhkMFI1ZWxKMk1VWlBjbGRhUXpWd1lXcGFkbXBaTUhveFprSjRNazVHZURWcFFVOW9UM2h5UVVodU5FcGtSakprUjFCQldYTXJkMUJzTURnMWJtSlZjMFpoUTBkbksyUlFPWEZ5YUZBdlkzTkVZMEl5Vm5nd2NrWmtOMXB3WXowOEwwMXZaSFZzZFhNXHUwMDJCUEVWNGNHOXVaVzUwUGtGUlFVSThMMFY0Y0c5dVpXNTBQanhRUG5kclVuRnFjU3RIWm5RMGVYRnBha05LVWxwQmMzUldTblJYTWt4VmNUbExWazUyVm1SMWFHdHVUaTgwWW5SeU5pdHlTbGwyT0ZKQ1RGWk1jM2t5VVVsMFNEQm5iMU53UkVnMmVGSldSbTlGY0hsbmRWWlJQVDA4TDFBXHUwMDJCUEZFXHUwMDJCZDJoSFVXbE1Na2x4TDBGV1RUVk5aRnBxY1ZoMGFWaG5UMDlWV0dGNFZYb3lWRlZOVGpkNVJGWTBPVkY0Y1c5SFRHOWtaalJzZWtRMWFVRjRVM2QzWldKd2ExUk5lSFpTV0ZWdGJtbElOM2h4TDNwV1QzYzlQVHd2VVQ0OFJGQVx1MDAyQmRIQnpaVEp1Tms1WGQxYzNPVUY1V2paamFWRkRhMjVKYm1wNVdrbExSR0Z4ZDJReFJVOHJSRmMxTlM4MVNuWTRTRTVwTVRaYVVYUmxPVUZrS3pGV1RtaFlTekF3UTJ4emNsRkpTamxPVFdzeWIyTXZabEU5UFR3dlJGQVx1MDAyQlBFUlJQbWhyVDJGeFJTOW5jRE4yVWxoNk5IWjJPVTVZZEUxblpHbGFPVTVvVjA1Rk0wMW9jbkpJTHpaeGJrSlljRk53Y1ZodVUwRk1UalppUm1KSkswTkVjbHBNZUVWMWFrWlNOV3MzTTNGaU1pOU5RMWcxUW10M1BUMDhMMFJSUGp4SmJuWmxjbk5sVVQ1VVZYSmtkVXBwZFZnNFZWRkthbmhtTVhZelVYVktPRGhrTWxwMGNWTnhkemxCUjI1R1drcFhXSEZGUkZGYVJXdDRkRFF4WldnMVduSTVjMVpJU21wcldrTnRRMlJxYTNCWlR6TTJhV1ZIWTBsRVFWQnhVVDA5UEM5SmJuWmxjbk5sVVQ0OFJENWFaRlpQYmxGMmFFeERTR0Z6UTNCSFRUVm9kMDFHV25aRU0zSmFiRGh5VXpWdk1FMUtkbmhPVEc5c2QwSlRNMjVpYXpNdmJVdG1lbFY0UVV0RFNFbHJXazR6YlV0VlFXNVFVMGRsU0UwMVUwWnFkeTkzWms0NU1XRXdZMUZOVTFFNWMwOHpiWFozWjNwemVIUldaMHMxTTFaUVQzUlphRkV5VlN0UFVVdEtNRzVPVWpkRk5qUlZhVXQwYzNSWU9FRk1TVWxJYVdaRVpqUnBibGN3WTFoaVJYQnBTMnBzYWk5a2VXczlQQzlFUGp3dlVsTkJTMlY1Vm1Gc2RXVVx1MDAyQiIsIlB1YmxpY0tleSI6IlBGSlRRVXRsZVZaaGJIVmxQanhOYjJSMWJIVnpQbXN3VlhNcldGTmhja0p0VFhkcVRHUXdMMFJSV1RFM0wxWnhlSFJtYnpoaVZsSndlV2cyYW5ZMWFTOXZWRFp1UVhsaE5VVnpiRzVFYkZWQ1NtbEJZVWt2UTFOM05YWm9OekkyVjNwWGQwUjVlbEoyTVVaUGNsZGFRelZ3WVdwYWRtcFpNSG94WmtKNE1rNUdlRFZwUVU5b1QzaHlRVWh1TkVwa1JqSmtSMUJCV1hNcmQxQnNNRGcxYm1KVmMwWmhRMGRuSzJSUU9YRnlhRkF2WTNORVkwSXlWbmd3Y2taa04xcHdZejA4TDAxdlpIVnNkWE1cdTAwMkJQRVY0Y0c5dVpXNTBQa0ZSUVVJOEwwVjRjRzl1Wlc1MFBqd3ZVbE5CUzJWNVZtRnNkV1VcdTAwMkIiLCJQcml2YXRlS2V5UGVtIjoiLS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLVxuTUlJQ1hRSUJBQUtCZ1FDVFJTejVkSnFzR1l6Q010M1Q4TkJqWHY5V3JHMVx1MDAyQmp4dFZHbktIcU8vbUxcdTAwMkJoUHFjREpcbnJrU3lXY09WUUVtSUJvajhKTERtXHUwMDJCSHZicGJOYkFQTE5HL1VVNnRaa0xtbHFObVx1MDAyQk5qVFBWOEhIWTBYSG1JQTZFXG43R3NBZWZnbDBYWjBZOEJpejdBXHUwMDJCWFR6bWR0U3dWb0lhRDUwLzJxdUUvOXl3TndIWlhIU3NWM3RtbHdJREFRQUJcbkFvR0FaZFZPblF2aExDSGFzQ3BHTTVod01GWnZEM3JabDhyUzVvME1KdnhOTG9sd0JTM25iazMvbUtmelV4QUtcbkNISWtaTjNtS1VBblBTR2VITTVTRmp3L3dmTjkxYTBjUU1TUTlzTzNtdndnenN4dFZnSzUzVlBPdFloUTJVXHUwMDJCT1xuUUtKMG5OUjdFNjRVaUt0c3RYOEFMSUlIaWZEZjRpblcwY1hiRXBpS2psai9keWtDUVFEQ1JHcU9yNFpcdTAwMkIzaktxXG5LTUlsRmtDeTFVbTFiWXRTcjBwVTI5VjI2R1NjMy9odTJ2cjZzbGkveEVFdFV1ekxaQWkwZlNDaEtrTWZyRkZVXG5XZ1NuS0M1VkFrRUF3aEdRaUwySXEvQVZNNU1kWmpxWHRpWGdPT1VYYXhVejJUVU1ON3lEVjQ5UXhxb0dMb2RmXG40bHpENWlBeFN3d2VicGtUTXh2UlhVbW5pSDd4cS96Vk93SkJBTGFiSHRwXHUwMDJCalZzRnUvUU1tZW5Ja0FwSnlKNDhcbm1TQ2cycXNIZFJEdmcxdWVmXHUwMDJCU2IvQnpZdGVtVUxYdlFIZnRWVFlWeXROQXBiSzBDQ2ZUVEpOcUhQMzBDUVFDR1xuUTVxb1RcdTAwMkJDbmU5RmZQaVx1MDAyQi8wMWUweUIySm4wMkZZMFRjeUd1c2YvcXFjRmVsS21wZWRJQXMzcHNWc2o0SU90a3ZcbkVTNk1WSG1UdmVwdmI4d0pma0dUQWtCTlN0MjRtSzVmeFJBbVBGL1cvZEM0bnp4M1ptMnBLckQwQWFjVmtsWmVcbm9RTkJrU1RHM2pWNkhsbXYyeFVjbU9Sa0tZSjJPU2xnN2ZxSjRad2dNQVx1MDAyQnBcbi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tIiwiUHVibGljS2V5UGVtIjoiLS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS1cbk1JR2ZNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0R05BRENCaVFLQmdRQ1RSU3o1ZEpxc0dZekNNdDNUOE5Calh2OVdcbnJHMVx1MDAyQmp4dFZHbktIcU8vbUxcdTAwMkJoUHFjREpya1N5V2NPVlFFbUlCb2o4SkxEbVx1MDAyQkh2YnBiTmJBUExORy9VVTZ0WmtcbkxtbHFObVx1MDAyQk5qVFBWOEhIWTBYSG1JQTZFN0dzQWVmZ2wwWFowWThCaXo3QVx1MDAyQlhUem1kdFN3Vm9JYUQ1MC8ycXVFXG4vOXl3TndIWlhIU3NWM3RtbHdJREFRQUJcbi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLSJ9
            //設定UOFX服務的URL
            UofxService.UofxServerUrl = "https://demox3.edetw.com/";

            UofxService.Key = "eyJDbGllbnRJZCI6IjY2YTM4MzFjLTQyNTMtNGQxZC0xYmIyLTA4ZGM2OGVjZjA1NCIsIlByaXZhdGVLZXkiOiJQRkpUUVV0bGVWWmhiSFZsUGp4TmIyUjFiSFZ6UG1zd1ZYTXJXRk5oY2tKdFRYZHFUR1F3TDBSUldURTNMMVp4ZUhSbWJ6aGlWbEp3ZVdnMmFuWTFhUzl2VkRadVFYbGhOVVZ6Ykc1RWJGVkNTbWxCWVVrdlExTjNOWFpvTnpJMlYzcFhkMFI1ZWxKMk1VWlBjbGRhUXpWd1lXcGFkbXBaTUhveFprSjRNazVHZURWcFFVOW9UM2h5UVVodU5FcGtSakprUjFCQldYTXJkMUJzTURnMWJtSlZjMFpoUTBkbksyUlFPWEZ5YUZBdlkzTkVZMEl5Vm5nd2NrWmtOMXB3WXowOEwwMXZaSFZzZFhNXHUwMDJCUEVWNGNHOXVaVzUwUGtGUlFVSThMMFY0Y0c5dVpXNTBQanhRUG5kclVuRnFjU3RIWm5RMGVYRnBha05LVWxwQmMzUldTblJYTWt4VmNUbExWazUyVm1SMWFHdHVUaTgwWW5SeU5pdHlTbGwyT0ZKQ1RGWk1jM2t5VVVsMFNEQm5iMU53UkVnMmVGSldSbTlGY0hsbmRWWlJQVDA4TDFBXHUwMDJCUEZFXHUwMDJCZDJoSFVXbE1Na2x4TDBGV1RUVk5aRnBxY1ZoMGFWaG5UMDlWV0dGNFZYb3lWRlZOVGpkNVJGWTBPVkY0Y1c5SFRHOWtaalJzZWtRMWFVRjRVM2QzWldKd2ExUk5lSFpTV0ZWdGJtbElOM2h4TDNwV1QzYzlQVHd2VVQ0OFJGQVx1MDAyQmRIQnpaVEp1Tms1WGQxYzNPVUY1V2paamFWRkRhMjVKYm1wNVdrbExSR0Z4ZDJReFJVOHJSRmMxTlM4MVNuWTRTRTVwTVRaYVVYUmxPVUZrS3pGV1RtaFlTekF3UTJ4emNsRkpTamxPVFdzeWIyTXZabEU5UFR3dlJGQVx1MDAyQlBFUlJQbWhyVDJGeFJTOW5jRE4yVWxoNk5IWjJPVTVZZEUxblpHbGFPVTVvVjA1Rk0wMW9jbkpJTHpaeGJrSlljRk53Y1ZodVUwRk1UalppUm1KSkswTkVjbHBNZUVWMWFrWlNOV3MzTTNGaU1pOU5RMWcxUW10M1BUMDhMMFJSUGp4SmJuWmxjbk5sVVQ1VVZYSmtkVXBwZFZnNFZWRkthbmhtTVhZelVYVktPRGhrTWxwMGNWTnhkemxCUjI1R1drcFhXSEZGUkZGYVJXdDRkRFF4WldnMVduSTVjMVpJU21wcldrTnRRMlJxYTNCWlR6TTJhV1ZIWTBsRVFWQnhVVDA5UEM5SmJuWmxjbk5sVVQ0OFJENWFaRlpQYmxGMmFFeERTR0Z6UTNCSFRUVm9kMDFHV25aRU0zSmFiRGh5VXpWdk1FMUtkbmhPVEc5c2QwSlRNMjVpYXpNdmJVdG1lbFY0UVV0RFNFbHJXazR6YlV0VlFXNVFVMGRsU0UwMVUwWnFkeTkzWms0NU1XRXdZMUZOVTFFNWMwOHpiWFozWjNwemVIUldaMHMxTTFaUVQzUlphRkV5VlN0UFVVdEtNRzVPVWpkRk5qUlZhVXQwYzNSWU9FRk1TVWxJYVdaRVpqUnBibGN3WTFoaVJYQnBTMnBzYWk5a2VXczlQQzlFUGp3dlVsTkJTMlY1Vm1Gc2RXVVx1MDAyQiIsIlB1YmxpY0tleSI6IlBGSlRRVXRsZVZaaGJIVmxQanhOYjJSMWJIVnpQbXN3VlhNcldGTmhja0p0VFhkcVRHUXdMMFJSV1RFM0wxWnhlSFJtYnpoaVZsSndlV2cyYW5ZMWFTOXZWRFp1UVhsaE5VVnpiRzVFYkZWQ1NtbEJZVWt2UTFOM05YWm9OekkyVjNwWGQwUjVlbEoyTVVaUGNsZGFRelZ3WVdwYWRtcFpNSG94WmtKNE1rNUdlRFZwUVU5b1QzaHlRVWh1TkVwa1JqSmtSMUJCV1hNcmQxQnNNRGcxYm1KVmMwWmhRMGRuSzJSUU9YRnlhRkF2WTNORVkwSXlWbmd3Y2taa04xcHdZejA4TDAxdlpIVnNkWE1cdTAwMkJQRVY0Y0c5dVpXNTBQa0ZSUVVJOEwwVjRjRzl1Wlc1MFBqd3ZVbE5CUzJWNVZtRnNkV1VcdTAwMkIiLCJQcml2YXRlS2V5UGVtIjoiLS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLVxuTUlJQ1hRSUJBQUtCZ1FDVFJTejVkSnFzR1l6Q010M1Q4TkJqWHY5V3JHMVx1MDAyQmp4dFZHbktIcU8vbUxcdTAwMkJoUHFjREpcbnJrU3lXY09WUUVtSUJvajhKTERtXHUwMDJCSHZicGJOYkFQTE5HL1VVNnRaa0xtbHFObVx1MDAyQk5qVFBWOEhIWTBYSG1JQTZFXG43R3NBZWZnbDBYWjBZOEJpejdBXHUwMDJCWFR6bWR0U3dWb0lhRDUwLzJxdUUvOXl3TndIWlhIU3NWM3RtbHdJREFRQUJcbkFvR0FaZFZPblF2aExDSGFzQ3BHTTVod01GWnZEM3JabDhyUzVvME1KdnhOTG9sd0JTM25iazMvbUtmelV4QUtcbkNISWtaTjNtS1VBblBTR2VITTVTRmp3L3dmTjkxYTBjUU1TUTlzTzNtdndnenN4dFZnSzUzVlBPdFloUTJVXHUwMDJCT1xuUUtKMG5OUjdFNjRVaUt0c3RYOEFMSUlIaWZEZjRpblcwY1hiRXBpS2psai9keWtDUVFEQ1JHcU9yNFpcdTAwMkIzaktxXG5LTUlsRmtDeTFVbTFiWXRTcjBwVTI5VjI2R1NjMy9odTJ2cjZzbGkveEVFdFV1ekxaQWkwZlNDaEtrTWZyRkZVXG5XZ1NuS0M1VkFrRUF3aEdRaUwySXEvQVZNNU1kWmpxWHRpWGdPT1VYYXhVejJUVU1ON3lEVjQ5UXhxb0dMb2RmXG40bHpENWlBeFN3d2VicGtUTXh2UlhVbW5pSDd4cS96Vk93SkJBTGFiSHRwXHUwMDJCalZzRnUvUU1tZW5Ja0FwSnlKNDhcbm1TQ2cycXNIZFJEdmcxdWVmXHUwMDJCU2IvQnpZdGVtVUxYdlFIZnRWVFlWeXROQXBiSzBDQ2ZUVEpOcUhQMzBDUVFDR1xuUTVxb1RcdTAwMkJDbmU5RmZQaVx1MDAyQi8wMWUweUIySm4wMkZZMFRjeUd1c2YvcXFjRmVsS21wZWRJQXMzcHNWc2o0SU90a3ZcbkVTNk1WSG1UdmVwdmI4d0pma0dUQWtCTlN0MjRtSzVmeFJBbVBGL1cvZEM0bnp4M1ptMnBLckQwQWFjVmtsWmVcbm9RTkJrU1RHM2pWNkhsbXYyeFVjbU9Sa0tZSjJPU2xnN2ZxSjRad2dNQVx1MDAyQnBcbi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tIiwiUHVibGljS2V5UGVtIjoiLS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS1cbk1JR2ZNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0R05BRENCaVFLQmdRQ1RSU3o1ZEpxc0dZekNNdDNUOE5Calh2OVdcbnJHMVx1MDAyQmp4dFZHbktIcU8vbUxcdTAwMkJoUHFjREpya1N5V2NPVlFFbUlCb2o4SkxEbVx1MDAyQkh2YnBiTmJBUExORy9VVTZ0WmtcbkxtbHFObVx1MDAyQk5qVFBWOEhIWTBYSG1JQTZFN0dzQWVmZ2wwWFowWThCaXo3QVx1MDAyQlhUem1kdFN3Vm9JYUQ1MC8ycXVFXG4vOXl3TndIWlhIU3NWM3RtbHdJREFRQUJcbi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLSJ9";

            EmplQueryRequestModel model = new EmplQueryRequestModel();
            model.UserCode = "woodman";
            model.CorpCode = "UOFXTraining0429";

            var emp= await UofxService.BASE.OrgEmpl.GetDept(model);

            var dept = emp.Depts.FirstOrDefault();


            var file = await UofxService.File.FileUpload
                ("D:/採購資訊.pdf");

            var item = new FileItem() { Id = file.Id, FileName = file.FileName };

            List<FileItem> fileList = new List<FileItem>();
            fileList.Add(item);

            string msg = "";

            try
            {
                string traceid = await UofxService.BPM.ApplyForm(
                    new UofxFormSchema()
                    {
                        Account = "woodman",
                        DeptCode = dept.Code,
                        AttachFiles = fileList,
                        Fields =
                        { C002=DateTime.Today,
                         C003="小黃",C004="高雄市前鎮區.."
                         }

                    }
                    );

                msg += "\r\n" + $"It is success.";
                msg += "\r\n" + $"Trace Id: {traceid}";
            }
            catch(Exception ex)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                var errorModel = UofxService.Error.ConvertToModel(ex);
                msg += "\r\n" + UofxService.Json.Convert(errorModel);
            }

            Console.WriteLine(msg);
        }
    }
}